export function IrancellIdentityProfileCompletionPage({onNavigate}){
 const{state,dispatch}=useIrancellStore();
 const currentUser=state.identity.usersById[state.session.currentUserId]||{};
 const role=state.session.activeRole||'student';
 const requiresFamilyApproval=role==='student';
 const[username,setUsername]=useState(currentUser.id||'');
 const[password,setPassword]=useState('');
 const[passwordConfirmation,setPasswordConfirmation]=useState('');
 const[submitted,setSubmitted]=useState(false);
 const usernameError=submitted?IrancellValidateRequired(username,'نام کاربری'):'';
 const passwordError=submitted&&password.length<6?'رمز عبور باید حداقل ۶ نویسه داشته باشد.':'';
 const confirmationError=submitted?(!passwordConfirmation?'تکرار رمز عبور را وارد کنید.':passwordConfirmation!==password?'تکرار رمز عبور با رمز عبور یکسان نیست.':''):'';
 function submit(event){event.preventDefault();setSubmitted(true);if(IrancellValidateRequired(username)||password.length<6||!passwordConfirmation||passwordConfirmation!==password)return;dispatch(IrancellAuthCompleteRegistration(username,password));if(requiresFamilyApproval){dispatch(IrancellAuthRequestOtp(IRANCELL_APP_CONFIG.demoAccounts.parent,'family-approval'));onNavigate('auth/otp?flow=family-approval&next=relationship-linking');return}onNavigate('relationship-linking')}
 return <IrancellIdentityFrame className="ir-credential-page"><section className="ir-credential-page__panel"><header className="ir-credential-page__top"><button type="button" aria-label="بازگشت" onClick={()=>onNavigate('role-select')}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m9 18 6-6-6-6"/></svg></button><span>مرحله ۳ از ۳</span></header><section className="ir-credential-page__heading"><span className="ir-credential-page__shield"><ShieldCheck size={28}/></span><h1>ایجاد اطلاعات ورود</h1><p>یک نام کاربری و رمز عبور امن برای ورودهای بعدی بسازید.</p></section><article className="ir-credential-page__identity"><span>{String(currentUser.name||'ک').charAt(0)}</span><div><strong>{currentUser.name||'کاربر جدید'}</strong><small>{IRANCELL_ROLE_LABELS[role]||'کاربر ایرانسل آکادمی'}</small></div><b>هویت تأییدشده</b></article><form className="ir-credential-page__form" onSubmit={submit} noValidate><IrancellInput label="نام کاربری" name="identity-username" value={username} onChange={event=>setUsername(event.target.value)} error={usernameError} helper="از حروف انگلیسی، عدد و خط تیره استفاده کنید." autoComplete="username"/><IrancellIdentityPasswordField label="رمز عبور" name="identity-password" value={password} onChange={event=>setPassword(event.target.value)} error={passwordError} autoComplete="new-password"/><IrancellIdentityPasswordField label="تکرار رمز عبور" name="identity-password-confirmation" value={passwordConfirmation} onChange={event=>setPasswordConfirmation(event.target.value)} error={confirmationError} autoComplete="new-password"/>{requiresFamilyApproval&&<IrancellIdentityLinkedAccount>پس از ذخیره، تأیید خانواده برای فعال‌سازی حساب درخواست می‌شود.</IrancellIdentityLinkedAccount>}<button type="submit" className="ir-credential-page__submit">ذخیره و ادامه</button></form><aside className="ir-credential-page__security"><LockKeyhole size={18}/><span>اطلاعات ورود رمزنگاری می‌شود و فقط برای احراز هویت حساب استفاده خواهد شد.</span></aside></section></IrancellIdentityFrame>
}