const IRANCELL_PAGE_DASHBOARD_META={
 student:{title:'سلام، آماده‌ای یادگیری را شروع کنیم؟',description:'سؤالت را بپرس، مسیر امروزت را ادامه بده و در صورت نیاز مدرس تأییدشده پیدا کن.',primary:'student/ask',primaryLabel:'پرسیدن سؤال',secondary:'student/learning',secondaryLabel:'ادامه یادگیری',classesTitle:'کلاس‌های پیش رو',actions:[{t:'درخواست مدرس',d:'نیاز، زمان و فوریت را ثبت کن.',r:'student/requests'},{t:'مقایسه مدرس‌ها',d:'مدرس‌ها و آموزشگاه‌های تأییدشده را ببین.',r:'student/teachers'},{t:'مرکز اعلان‌ها',d:'کلاس‌ها و اقدام‌های حساس را از دست نده.',r:'notifications'}]},
 parent:{title:'داشبورد خانواده',description:'وضعیت فرزند، رضایت‌ها، پرداخت‌های امانی و کلاس‌ها را یکجا دنبال کنید.',primary:'parent/consents',primaryLabel:'بررسی رضایت‌ها',secondary:'parent/payments',secondaryLabel:'پرداخت‌ها',classesTitle:'کلاس‌های فرزند',actions:[{t:'فرزندان من',d:'رابطه‌های تأییدشده و وضعیت تحصیلی را ببینید.',r:'parent/children'},{t:'رضایت‌های در انتظار',d:'مجوزهای لازم برای کلاس را بررسی و امضا کنید.',r:'parent/consents'},{t:'ثبت و پیگیری شکایت',d:'مشکل کلاس یا پرداخت را امن پیگیری کنید.',r:'parent/complaints'}]},
 teacher:{title:'مرکز کار مدرس',description:'درخواست‌های مرتبط، پیشنهادها، تقویم و کیفیت تدریس خود را مدیریت کنید.',primary:'teacher/requests',primaryLabel:'مشاهده درخواست‌ها',secondary:'teacher/calendar',secondaryLabel:'تقویم تدریس',classesTitle:'جلسه‌های تدریس',actions:[{t:'ثبت و مدیریت پیشنهادها',d:'برای درخواست‌های مرتبط پیشنهاد شفاف ارسال کنید.',r:'teacher/offers'},{t:'کلاس‌های من',d:'جلسه‌های زمان‌بندی‌شده و تکمیل‌شده را مدیریت کنید.',r:'teacher/classes'},{t:'کیفیت و بازخورد',d:'امتیازها، گزارش‌ها و اقدام‌های بهبود را ببینید.',r:'teacher/quality'}]},
 academy:{title:'مدیریت آموزشگاه',description:'تقاضا، مدرس‌ها، کلاس‌ها، SLA و تسویه تجمیعی را کنترل کنید.',primary:'academy/requests',primaryLabel:'تقاضاهای جدید',secondary:'academy/teachers',secondaryLabel:'مدیریت مدرس‌ها',classesTitle:'کلاس‌های آموزشگاه',actions:[{t:'پیشنهادهای آموزشگاه',d:'پیشنهادهای قیمت و مدرس تخصیص‌یافته را مدیریت کنید.',r:'academy/offers'},{t:'مدیریت کلاس‌ها',d:'زمان‌بندی، حضور و تحویل خدمت را پیگیری کنید.',r:'academy/classes'},{t:'گزارش عملکرد',d:'کیفیت، تبدیل و تسویه را یکجا ببینید.',r:'academy/reports'}]},
 'content-provider':{title:'استودیوی محتوا',description:'محتوا را منتشر کنید، کیفیت و بازدید را بسنجید و درآمد را پیگیری کنید.',primary:'content/upload',primaryLabel:'بارگذاری محتوا',secondary:'content/library',secondaryLabel:'کتابخانه من',classesTitle:'محتوای در اولویت',actions:[{t:'کتابخانه محتوا',d:'وضعیت انتشار و نسخه‌های محتوا را مدیریت کنید.',r:'content/library'},{t:'تحلیل محتوا',d:'بازدید، تکمیل و امتیاز محتوا را بررسی کنید.',r:'content/analytics'},{t:'تسویه درآمد',d:'درآمد قابل پرداخت و سابقه تسویه را ببینید.',r:'content/payouts'}]},
 admin:{title:'مرکز عملیات و کیفیت',description:'سلامت سرویس، کاربران، تأمین‌کنندگان، پرداخت و شکایت را پایش کنید.',primary:'admin/system',primaryLabel:'سلامت سامانه',secondary:'admin/complaints',secondaryLabel:'صف شکایت‌ها',classesTitle:'کلاس‌های تحت پایش',actions:[{t:'مدیریت کاربران',d:'دسترسی و وضعیت حساب‌ها را بررسی کنید.',r:'admin/users'},{t:'تأمین‌کنندگان',d:'احراز و تعلیق مدرس‌ها و آموزشگاه‌ها را مدیریت کنید.',r:'admin/providers'},{t:'گزارش‌های مدیریتی',d:'شاخص‌های قیف، درآمد و کیفیت را تحلیل کنید.',r:'admin/reports'}]}
};
export function IrancellRoleDashboardSections({role,onNavigate}){
 const{state}=useIrancellStore();
 const meta=IRANCELL_PAGE_DASHBOARD_META[role]||IRANCELL_PAGE_DASHBOARD_META.student;
 const fallbackIds={student:'student-1',parent:'parent-1',teacher:'teacher-1',academy:'academy-1','content-provider':'content-1',admin:'admin-1'};
 const actorId=state.session.currentUserId||fallbackIds[role];
 const classes=Object.values(state.classroom.sessionsById);
 const requests=Object.values(state.marketplace.requestsById);
 const payments=Object.values(state.payment.paymentsById);
 const contents=Object.values(state.content.catalogueById);
 const relationships=Object.values(state.identity.relationshipsById);
 const consents=Object.values(state.consent.gatesBySessionId);
 const reports=state.admin.reports;
 const studentClasses=classes.filter(item=>item.studentId===actorId);
 const providerClasses=classes.filter(item=>item.providerId===actorId);
 const managedChildIds=relationships.filter(item=>item.parentId===actorId&&item.status==='active').map(item=>item.childId);
 const parentClasses=classes.filter(item=>managedChildIds.includes(item.studentId));
 const parentSessionIds=new Set(parentClasses.map(item=>item.id));
 const parentConsents=consents.filter(item=>parentSessionIds.has(item.sessionId));
 const parentPayments=payments.filter(item=>parentSessionIds.has(item.sessionId));
 const visibleClasses=role==='student'?studentClasses:role==='parent'?parentClasses:role==='teacher'||role==='academy'?providerClasses:classes;
 const roleStats=role==='admin'?[{label:'کاربر فعال ماهانه',value:IrancellFormatPersianNumber(reports.mau),icon:Users},{label:'ارزش تراکنش',value:IrancellFormatCurrency(reports.gmv),icon:WalletCards},{label:'موفقیت کلاس',value:`${IrancellFormatPersianNumber(reports.classSuccess)}٪`,icon:Activity},{label:'حل توسط چیستی',value:`${IrancellFormatPersianNumber(reports.chistiResolution)}٪`,icon:TrendingUp}]:role==='parent'?[{label:'فرزند متصل',value:IrancellFormatPersianNumber(managedChildIds.length),icon:UsersRound},{label:'رضایت در انتظار',value:IrancellFormatPersianNumber(parentConsents.filter(item=>item.status!=='signed').length),icon:ShieldCheck},{label:'پرداخت در انتظار',value:IrancellFormatPersianNumber(parentPayments.filter(item=>item.status==='pending').length),icon:WalletCards},{label:'کلاس‌های فعال',value:IrancellFormatPersianNumber(parentClasses.length),icon:CalendarCheck}]:role==='teacher'||role==='academy'?[{label:'جلسه‌های من',value:IrancellFormatPersianNumber(providerClasses.length),icon:CalendarCheck},{label:'درخواست‌های بازار',value:IrancellFormatPersianNumber(requests.length),icon:GraduationCap},{label:'کیفیت خدمت',value:`${IrancellFormatPersianNumber(state.quality.qualityScoresByProviderId[actorId]||0)}٪`,icon:Activity},{label:'پیشنهادهای ثبت‌شده',value:IrancellFormatPersianNumber(Object.values(state.marketplace.offersById).filter(item=>item.providerId===actorId).length),icon:TrendingUp}]:role==='content-provider'?[{label:'محتوای منتشرشده',value:IrancellFormatPersianNumber(contents.filter(item=>item.status==='published').length),icon:BookOpen},{label:'بازدید کل',value:IrancellFormatPersianNumber(contents.reduce((sum,item)=>sum+(Number(item.views)||0),0)),icon:TrendingUp},{label:'میانگین امتیاز',value:(contents.reduce((sum,item)=>sum+(Number(item.rating)||0),0)/Math.max(contents.length,1)).toLocaleString('fa-IR',{maximumFractionDigits:1}),icon:Activity},{label:'در انتظار بررسی',value:IrancellFormatPersianNumber(contents.filter(item=>item.status!=='published').length),icon:ShieldCheck}]:[{label:'کلاس‌های فعال',value:IrancellFormatPersianNumber(studentClasses.length),icon:CalendarCheck},{label:'درخواست‌های من',value:IrancellFormatPersianNumber(requests.filter(item=>item.studentId===actorId).length),icon:GraduationCap},{label:'پیشرفت محتوا',value:`${IrancellFormatPersianNumber(Math.round(Object.values(state.content.watchProgress).reduce((sum,value)=>sum+(Number(value)||0),0)/Math.max(Object.keys(state.content.watchProgress).length,1)))}٪`,icon:BookOpen},{label:'اعلان خوانده‌نشده',value:IrancellFormatPersianNumber(state.notifications.unreadCount||0),icon:ShieldCheck}];
 return <><IrancellPageHeader eyebrow={IRANCELL_ROLE_LABELS[role]} title={meta.title} description={meta.description} actions={<><IrancellButton onClick={()=>onNavigate(meta.primary)}>{meta.primaryLabel}</IrancellButton><IrancellButton variant="secondary" onClick={()=>onNavigate(meta.secondary)}>{meta.secondaryLabel}</IrancellButton></>}/><IrancellTrustStrip/><div className="ir-stats-grid">{roleStats.map(item=><IrancellStatCard key={item.label}{...item}/>)}</div><div className="ir-dashboard-grid"><IrancellCard title={meta.classesTitle} subtitle="نمایش این بخش بر اساس نقش فعال و داده‌های فروشگاه مرکزی فیلتر شده است.">{visibleClasses.length?visibleClasses.slice(0,3).map(item=><article className="ir-list-row" key={item.id}><div><strong>{item.title}</strong><small>{new Date(item.startAt).toLocaleString('fa-IR')}</small></div><IrancellStatusBadge status={item.status}/><button type="button" onClick={()=>onNavigate(`class/${item.id}`)}>مشاهده</button></article>):<IrancellStatePanel title="مورد فعالی وجود ندارد" description="با ثبت درخواست یا تکمیل تنظیمات، موارد مرتبط اینجا نمایش داده می‌شوند."/>}</IrancellCard><IrancellCard title="اقدام‌های پیشنهادی" subtitle="میان‌برهای این بخش با نقش فعال هماهنگ هستند.">{meta.actions.map(item=><article className="ir-action-row" key={item.t}><div><strong>{item.t}</strong><small>{item.d}</small></div><button type="button" onClick={()=>onNavigate(item.r)}>باز کردن</button></article>)}</IrancellCard></div></>
}
