function IrancellRemoteGatewayTraceId(prefix='trace'){const source=typeof globalThis!=='undefined'?globalThis.crypto:null;return source&&typeof source.randomUUID==='function'?`${prefix}-${source.randomUUID()}`:`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,10)}`;}
function IrancellRemoteGatewayObject(value){return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function IrancellRemoteGatewayError(error,fallback={}){const source=IrancellRemoteGatewayObject(error)?error:{};const status=Number(source.status||fallback.status)||0;const code=String(source.code||source.errorCode||fallback.code||(status===401?'authentication_required':status===403?'permission_denied':status===404?'not_found':status===409?'conflict':status===422?'validation_error':status===429?'rate_limited':status>=500?'service_unavailable':'server_error'));return{code,message:String(source.message||fallback.message||'در ارتباط با سرویس مشکلی رخ داد.'),fieldErrors:IrancellRemoteGatewayObject(source.fieldErrors)?source.fieldErrors:{},status,retryable:typeof source.retryable==='boolean'?source.retryable:[0,408,425,429,500,502,503,504].includes(status),conflictVersion:source.conflictVersion||null,traceId:source.traceId||fallback.traceId||null};}
function IrancellRemoteGatewayDescriptor(operations,name,operation){return operations?.[`${name}.${operation}`]||operations?.[name]?.[operation]||operations?.[operation]||null;}
function IrancellRemoteGatewayUrl(baseUrl,path,query){const raw=String(path||'');const base=/^https?:\/\//i.test(raw)?raw:`${String(baseUrl||'').replace(/\/$/,'')}/${raw.replace(/^\//,'')}`;if(!query||typeof query!=='object')return base;const params=new URLSearchParams();Object.keys(query).forEach(key=>{const value=query[key];if(value===undefined||value===null||value==='')return;(Array.isArray(value)?value:[value]).forEach(item=>params.append(key,String(item)));});const suffix=params.toString();return suffix?`${base}${base.includes('?')?'&':'?'}${suffix}`:base;}
export class IrancellRemoteGateway{
 constructor(name,options={}){this.name=name;this.baseUrl=options.baseUrl??IRANCELL_APP_CONFIG.api.baseUrl;this.operations=options.operations||IRANCELL_APP_CONFIG.api.operations||{};this.credentials=options.credentials||IRANCELL_APP_CONFIG.api.credentials||'include';this.timeoutMs=Math.max(1000,Number(options.timeoutMs||IRANCELL_APP_CONFIG.api.timeoutMs)||15000);this.headers={...(IRANCELL_APP_CONFIG.api.headers||{}),...(options.headers||{})};}
 async request(operation,payload={},options={}){
  const traceId=options.traceId||IrancellRemoteGatewayTraceId(`${this.name}-request`);const adapter=options.adapter||(typeof globalThis!=='undefined'?globalThis.__IRANCELL_LMS_GATEWAY_ADAPTER__:null);
  if(typeof adapter==='function'){try{const result=await adapter({gateway:this.name,operation,payload,options,traceId});return result?.ok===false?{...result,error:IrancellRemoteGatewayError(result.error,{traceId})}:result?.ok===true?{...result,traceId:result.traceId||traceId}:{ok:true,data:result??null,meta:{adapter:true},traceId};}catch(error){return{ok:false,error:IrancellRemoteGatewayError(error,{code:'adapter_error',message:'آداپتور داده با خطا روبه‌رو شد.',traceId}),traceId};}}
  const raw=IrancellRemoteGatewayDescriptor(this.operations,this.name,operation);if(!raw)return{ok:false,error:IrancellRemoteGatewayError(null,{code:'backend_contract_missing',message:`عملیات ${this.name}.${operation} در پیکربندی سرویس تعریف نشده است.`,traceId}),traceId};
  const descriptor=typeof raw==='string'?{path:raw,method:'POST'}:raw;if(!descriptor?.path)return{ok:false,error:IrancellRemoteGatewayError(null,{code:'backend_contract_invalid',message:`قرارداد عملیات ${this.name}.${operation} معتبر نیست.`,traceId}),traceId};if(typeof fetch!=='function')return{ok:false,error:IrancellRemoteGatewayError(null,{code:'transport_unavailable',message:'امکان ارتباط شبکه در این محیط وجود ندارد.',traceId}),traceId};
  const method=String(options.method||descriptor.method||'POST').toUpperCase();const url=IrancellRemoteGatewayUrl(this.baseUrl,descriptor.path,method==='GET'||method==='HEAD'?payload:options.query);const controller=typeof AbortController==='function'?new AbortController():null;let timeoutId=null;if(controller)timeoutId=setTimeout(()=>controller.abort('timeout'),Number(options.timeoutMs)||this.timeoutMs);if(controller&&options.signal)options.signal.addEventListener('abort',()=>controller.abort(options.signal.reason),{once:true});
  const body=method==='GET'||method==='HEAD'?undefined:payload;const isForm=typeof FormData!=='undefined'&&body instanceof FormData;const headers={Accept:'application/json','X-Request-Id':options.requestId||traceId,'X-Trace-Id':traceId,...this.headers,...(descriptor.headers||{}),...(options.headers||{})};if(body!==undefined&&!isForm&&!headers['Content-Type'])headers['Content-Type']='application/json';if(options.idempotencyKey)headers['Idempotency-Key']=options.idempotencyKey;
  try{const response=await fetch(url,{method,credentials:options.credentials||descriptor.credentials||this.credentials,headers,body:body===undefined?undefined:isForm?body:JSON.stringify(body),signal:controller?.signal});const responseTraceId=response.headers.get('x-trace-id')||response.headers.get('x-request-id')||traceId;const contentType=response.headers.get('content-type')||'';const data=response.status===204?null:contentType.includes('application/json')?await response.json():await response.text().then(text=>text?{message:text}:null);if(!response.ok){const source=IrancellRemoteGatewayObject(data)?data.error||data:{};return{ok:false,error:IrancellRemoteGatewayError(source,{status:response.status,message:source.message||`درخواست با وضعیت ${response.status} ناموفق بود.`,traceId:responseTraceId}),traceId:responseTraceId};}return{ok:true,data:IrancellRemoteGatewayObject(data)&&Object.prototype.hasOwnProperty.call(data,'data')?data.data:data,meta:IrancellRemoteGatewayObject(data)?data.meta||{}:{},traceId:responseTraceId};}
  catch(error){const timedOut=controller?.signal?.aborted&&controller.signal.reason==='timeout';const offline=typeof navigator!=='undefined'&&navigator.onLine===false;return{ok:false,error:IrancellRemoteGatewayError(error,{code:timedOut?'timeout':offline?'offline':error?.name==='AbortError'?'request_cancelled':'network_error',message:timedOut?'زمان پاسخ سرویس به پایان رسید.':offline?'اتصال اینترنت برقرار نیست.':error?.name==='AbortError'?'درخواست لغو شد.':'ارتباط با سرویس برقرار نشد.',traceId}),traceId};}
  finally{if(timeoutId)clearTimeout(timeoutId);}
 }
}
