// Root import/export boundary for irancell-lms/App.
// The EDUS compiler shares top-level scope inside a repository, so implementation files do not repeat imports.

      
import {
  IRANCELL_ROLE_HOME_ROUTES,
  IRANCELL_ROLE_NAVIGATION,
  IrancellAuthSelectRole,
  IrancellHasPermissions,
  IrancellUseStore as useIrancellStore
} from 'irancell-lms/Core';
import {
  IrancellAppShell,
  IrancellButton,
  IrancellStatePanel,
  IrancellToastStack
} from 'irancell-lms/Component';
import {
  IrancellAcademyClassesPage,
  IrancellAcademyFinancePage,
  IrancellAcademyHomePage,
  IrancellAcademyOffersPage,
  IrancellAcademyProfilePage,
  IrancellAcademyReportsPage,
  IrancellAcademyRequestsPage,
  IrancellAcademyTeachersPage,
  IrancellAdminClassesPage,
  IrancellAdminComplaintsPage,
  IrancellAdminContentPage,
  IrancellAdminHomePage,
  IrancellAdminPaymentsPage,
  IrancellAdminProvidersPage,
  IrancellAdminReportsPage,
  IrancellAdminSettingsPage,
  IrancellAdminSystemPage,
  IrancellAdminUsersPage,
  IrancellContentProviderAnalyticsPage,
  IrancellContentProviderHomePage,
  IrancellContentProviderLibraryPage,
  IrancellContentProviderModerationPage,
  IrancellContentProviderPayoutsPage,
  IrancellContentProviderProfilePage,
  IrancellContentProviderUploadPage,
  IrancellIdentityLoginPage,
  IrancellIdentityOnboardingPage,
  IrancellIdentityOtpPage,
  IrancellIdentityProfileCompletionPage,
  IrancellIdentityRelationshipLinkingPage,
  IrancellIdentityRoleSelectPage,
  IrancellIdentitySplashPage,
  IrancellParentChildrenPage,
  IrancellParentClassesPage,
  IrancellParentComplaintsPage,
  IrancellParentConsentsPage,
  IrancellParentHomePage,
  IrancellParentPaymentsPage,
  IrancellParentProfilePage,
  IrancellParentReportsPage,
  IrancellSharedClassRoomPage,
  IrancellSharedComplaintPage,
  IrancellSharedConsentDetailsPage,
  IrancellSharedHelpPage,
  IrancellSharedNotificationsPage,
  IrancellSharedPaymentDetailsPage,
  IrancellSharedPrototypePage,
  IrancellSharedRatingPage,
  IRANCELL_PAGE_STUDENT_HOME_AVATAR,
  IrancellStudentAskPage,
  IrancellStudentChatsPage,
  IrancellStudentClassesPage,
  IrancellStudentContentDetailsPage,
  IrancellStudentHomePage,
  IrancellStudentLearningPage,
  IrancellStudentOffersPage,
  IrancellStudentProfilePage,
  IrancellStudentRequestsPage,
  IrancellStudentTeachersPage,
  IrancellTeacherCalendarPage,
  IrancellTeacherClassesPage,
  IrancellTeacherEarningsPage,
  IrancellTeacherHomePage,
  IrancellTeacherOffersPage,
  IrancellTeacherProfilePage,
  IrancellTeacherQualityPage,
  IrancellTeacherRequestsPage
} from 'irancell-lms/Page';

export {
  App,
  IrancellApplication,
  IRANCELL_BOOT_CONFIG,
  IrancellAppParseHashLocation,
  IrancellAppMatchRegisteredScreen,
  IrancellAppNavigateToRoute,
  IrancellAppResolveSafeHomeRoute,
  IrancellAppRuntime,
  IRANCELL_SCREEN_REGISTRY,
  IrancellScreenRegistryEntries
};
