export function IrancellPageHeader({eyebrow,title,description,actions,breadcrumbs=[]}){const labels={Observability:'پایش سامانه','اعلان‌های رویدادمحور':'مرکز پیام‌ها','اسکرو':'پرداخت امن','پرداخت امانی':'پرداخت امن','امضایی':'رضایت و مجوز','بازار مدرس':'انتخاب مدرس','مارکت‌پلیس':'درخواست کلاس','مقایسه پیشنهادها':'انتخاب پیشنهاد','بینایی':'یادگیری هوشمند','چیستی':'دستیار هوشمند','دیالوگی':'کلاس آنلاین','کیستی':'حساب کاربری','تحلیل محصول':'گزارش و تحلیل','رسیدگی':'پشتیبانی','کتابخانه محتوا':'مدیریت محتوا','کیفیت و بازیابی خدمت':'کنترل کیفیت','اعتماد و ایمنی':'امنیت و حریم خصوصی',academy:'آموزشگاه',admin:'مدیریت سامانه','content-provider':'تولید محتوا',parent:'خانواده',shared:'خدمات کاربری',teacher:'مدرس'};const visibleEyebrow=labels[eyebrow]||eyebrow;return <header className="ir-page-header">{breadcrumbs.length>0&&<nav aria-label="مسیر صفحه">{breadcrumbs.join(' / ')}</nav>}<div><div>{visibleEyebrow&&<span>{visibleEyebrow}</span>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{actions&&<aside>{actions}</aside>}</div></header>}
export function IrancellStatePanel({state='empty',title,description,action}){
 const Icon=state==='loading'?LoaderCircle:state==='success'?CheckCircle2:state==='warning'?AlertTriangle:state==='error'?AlertTriangle:state==='unauthorized'?LockKeyhole:state==='retry'?RefreshCw:Inbox;
 const iconIsRenderable=typeof Icon==='string'||typeof Icon==='function'||Boolean(Icon&&typeof Icon==='object'&&Icon.$$typeof);
 return <div className={`ir-state ir-state--${state}`} role={state==='error'?'alert':'status'}>{iconIsRenderable?React.createElement(Icon,{size:36}):<span className="ir-state__fallback-icon" aria-hidden="true">!</span>}<h3>{title}</h3>{description&&<p>{description}</p>}{action}</div>
}
export function IrancellSkeleton({lines=3}){return <div className="ir-skeleton" aria-label="در حال بارگذاری" aria-busy="true">{Array.from({length:lines}).map((_,index)=><span key={index}/>)}</div>}
export function IrancellSectionTitle({title,description,action}){return <div className="ir-section-title"><div><h2>{title}</h2>{description&&<p>{description}</p>}</div>{action}</div>}
export function IrancellPageScaffold({children,title,subtitle,onBack,actions,className='',fullBleed=false}){return <section className={`ir-ui-page-scaffold ${fullBleed?'is-full-bleed':''} ${className}`.trim()}>{(title||onBack||actions)&&<header className="ir-ui-page-scaffold__header">{onBack&&<button type="button" className="ir-ui-page-scaffold__back" onClick={onBack} aria-label="بازگشت"><span className="material-symbols-outlined" aria-hidden="true">arrow_forward</span></button>}<div>{title&&<h1>{title}</h1>}{subtitle&&<p>{subtitle}</p>}</div>{actions&&<aside>{actions}</aside>}</header>}<div className="ir-ui-page-scaffold__content">{children}</div></section>}
export function IrancellFilterTabs({items=[],value,onChange,ariaLabel='فیلترها'}){return <div className="ir-ui-filter-tabs" role="group" aria-label={ariaLabel}>{items.map(item=><button type="button" key={item.id} className={value===item.id?'is-active':''} aria-pressed={value===item.id} disabled={item.disabled} onClick={()=>onChange?.(item.id)}><span>{item.label}</span>{item.count!==undefined&&<b>{IrancellFormatPersianNumber(item.count)}</b>}</button>)}</div>}
export function IrancellToggleRow({title,description,checked,onChange,disabled=false,loading=false}){return <div className={`ir-ui-toggle-row ${disabled?'is-disabled':''}`}><div><strong>{title}</strong>{description&&<small>{description}</small>}</div><button type="button" role="switch" aria-checked={Boolean(checked)} aria-label={title} disabled={disabled||loading} className={checked?'is-on':''} onClick={()=>onChange?.(!checked)}><span/></button></div>}
export function IrancellStatusBanner({tone='info',title,children,action}){const Icon=tone==='success'?CheckCircle2:tone==='danger'?AlertTriangle:tone==='warning'?AlertTriangle:ShieldCheck;return <aside className={`ir-ui-status-banner is-${tone}`} role={tone==='danger'?'alert':'status'}><Icon size={21}/><div>{title&&<strong>{title}</strong>}{children&&<p>{children}</p>}</div>{action&&<span className="ir-ui-status-banner__action">{action}</span>}</aside>}
export function IrancellStateView({state='empty',title,description,action}){return <div className="ir-ui-state-view"><IrancellStatePanel state={state} title={title} description={description} action={action}/></div>}
export function IrancellBottomSheet({open,title,children,onClose,actions}){return <IrancellModal open={open} title={title} onClose={onClose} actions={actions} variant="sheet">{children}</IrancellModal>}
export function IrancellChistiComposer({value='',onChange,onSubmit,placeholder='سؤال خود را بنویسید…',loading=false,disabled=false,onAttach,attachmentName='',submitLabel='ارسال'}){function submit(event){event.preventDefault();if(!disabled&&!loading&&String(value||'').trim())onSubmit?.(event)}return <form className="ir-ui-chisti-composer" onSubmit={submit}><div>{attachmentName&&<small>پیوست: {attachmentName}</small>}<textarea value={value} onChange={event=>onChange?.(event.target.value)} placeholder={placeholder} disabled={disabled||loading} rows={1}/></div>{onAttach&&<button type="button" className="ir-ui-chisti-composer__attach" onClick={onAttach} disabled={disabled||loading} aria-label="افزودن پیوست"><UploadCloud size={20}/></button>}<IrancellButton type="submit" loading={loading} disabled={disabled||!String(value||'').trim()} size="sm">{submitLabel}</IrancellButton></form>}