export function IrancellPageHeader({eyebrow,title,description,actions,breadcrumbs=[],style={}}){
 const labels={Observability:'پایش سامانه','اعلان‌های رویدادمحور':'مرکز پیام‌ها','اسکرو':'پرداخت امن','پرداخت امانی':'پرداخت امن','امضایی':'رضایت و مجوز','بازار مدرس':'انتخاب مدرس','مارکت‌پلیس':'درخواست کلاس','مقایسه پیشنهادها':'انتخاب پیشنهاد','بینایی':'یادگیری هوشمند','چیستی':'دستیار هوشمند','دیالوگی':'کلاس آنلاین','کیستی':'حساب کاربری','تحلیل محصول':'گزارش و تحلیل','رسیدگی':'پشتیبانی','کتابخانه محتوا':'مدیریت محتوا','کیفیت و بازیابی خدمت':'کنترل کیفیت','اعتماد و ایمنی':'امنیت و حریم خصوصی',academy:'آموزشگاه',admin:'مدیریت سامانه','content-provider':'تولید محتوا',parent:'خانواده',shared:'خدمات کاربری',teacher:'مدرس'};
 const visibleEyebrow=labels[eyebrow]||eyebrow;
 const font='"Vazirmatn", Tahoma, Arial, sans-serif';
 return <header dir="rtl" style={{boxSizing:'border-box',display:'flex',width:'100%',minWidth:0,maxWidth:'none',flexDirection:'column',gap:'13px',margin:0,padding:'clamp(18px,3vw,28px)',direction:'rtl',color:'#202024',background:'rgba(255,255,255,.9)',border:'1px solid #E8E1C6',borderRadius:'24px',boxShadow:'0 12px 34px rgba(64,53,10,.07)',fontFamily:font,...style}}>
  {breadcrumbs.length>0&&<nav aria-label="مسیر صفحه" style={{display:'flex',width:'100%',minWidth:0,flexWrap:'wrap',alignItems:'center',gap:'6px',margin:0,color:'#85868D',fontFamily:font,fontSize:'11px',fontWeight:700,lineHeight:1.8}}>{breadcrumbs.map((item,index)=><React.Fragment key={`${item}-${index}`}><span>{item}</span>{index<breadcrumbs.length-1&&<span aria-hidden="true" style={{color:'#C0A400'}}>‹</span>}</React.Fragment>)}</nav>}
  <div style={{boxSizing:'border-box',display:'flex',width:'100%',minWidth:0,maxWidth:'none',flexWrap:'wrap',alignItems:'flex-end',justifyContent:'space-between',gap:'18px'}}>
   <div style={{minWidth:0,flex:'1 1 360px'}}>
    {visibleEyebrow&&<span style={{display:'inline-flex',alignItems:'center',minHeight:'28px',margin:'0 0 9px',padding:'4px 11px',color:'#665500',background:'#FFF4B5',border:'1px solid #EED66C',borderRadius:'999px',fontFamily:font,fontSize:'11px',fontWeight:900,lineHeight:1.5}}>{visibleEyebrow}</span>}
    <h1 style={{margin:0,overflowWrap:'anywhere',color:'#202024',fontFamily:font,fontSize:'clamp(23px,3vw,35px)',fontWeight:900,lineHeight:1.45}}>{title}</h1>
    {description&&<p style={{width:'100%',maxWidth:'760px',margin:'8px 0 0',color:'#707178',fontFamily:font,fontSize:'13px',fontWeight:500,lineHeight:1.95}}>{description}</p>}
   </div>
   {actions&&<aside style={{display:'flex',maxWidth:'100%',flex:'0 1 auto',flexWrap:'wrap',alignItems:'center',justifyContent:'flex-end',gap:'9px'}}>{actions}</aside>}
  </div>
 </header>
}
export function IrancellStatePanel({state='empty',title,description,action}){
 const Icon=state==='loading'?LoaderCircle:state==='success'?CheckCircle2:state==='warning'?AlertTriangle:state==='error'?AlertTriangle:state==='unauthorized'?LockKeyhole:state==='retry'?RefreshCw:Inbox;
 const iconIsRenderable=typeof Icon==='string'||typeof Icon==='function'||Boolean(Icon&&typeof Icon==='object'&&Icon.$$typeof);
 const font='"Vazirmatn", Tahoma, Arial, sans-serif',danger=state==='error'||state==='unauthorized',success=state==='success',warning=state==='warning'||state==='retry';
 return <div role={state==='error'?'alert':'status'} dir="rtl" style={{boxSizing:'border-box',display:'flex',width:'100%',minWidth:0,minHeight:'220px',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:'9px',margin:0,padding:'28px',textAlign:'center',color:'#202024',background:'#FFFFFF',border:`1px ${state==='empty'?'dashed':'solid'} ${danger?'#F1C7C7':success?'#BFE5CC':warning?'#F0D763':'#DDD7BD'}`,borderRadius:'20px',fontFamily:font}}>{iconIsRenderable?<span aria-hidden="true" style={{display:'grid',width:'58px',height:'58px',placeItems:'center',color:danger?'#A12626':success?'#21663D':warning?'#765F00':'#725F00',background:danger?'#FFF0F0':success?'#E9F7EE':warning?'#FFF7CE':'#FFF3AE',borderRadius:'18px'}}>{React.createElement(Icon,{size:31})}</span>:<span aria-hidden="true" style={{fontFamily:font,fontSize:'26px',fontWeight:900}}>!</span>}<h3 style={{margin:0,color:'#202024',fontFamily:font,fontSize:'16px',fontWeight:900,lineHeight:1.6}}>{title}</h3>{description&&<p style={{maxWidth:'520px',margin:0,color:'#777982',fontFamily:font,fontSize:'12px',fontWeight:500,lineHeight:1.9}}>{description}</p>}{action&&<div style={{display:'flex',maxWidth:'100%',marginTop:'6px',alignItems:'center',justifyContent:'center'}}>{action}</div>}</div>
}
export function IrancellSkeleton({lines=3}){return <div aria-label="در حال بارگذاری" aria-busy="true" style={{boxSizing:'border-box',display:'grid',width:'100%',minWidth:0,gap:'10px',margin:0,padding:'16px',background:'#FFFFFF',border:'1px solid #E7E2CC',borderRadius:'18px'}}>{Array.from({length:lines}).map((_,index)=><span key={index} style={{display:'block',width:index===lines-1?'64%':'100%',height:'14px',background:'#EEEDE8',borderRadius:'999px'}}/>)}</div>}
export function IrancellSectionTitle({title,description,action}){const font='"Vazirmatn", Tahoma, Arial, sans-serif';return <header dir="rtl" style={{boxSizing:'border-box',display:'flex',width:'100%',minWidth:0,maxWidth:'none',flexWrap:'wrap',alignItems:'flex-end',justifyContent:'space-between',gap:'12px',margin:0,padding:'0 0 12px',borderBottom:'1px solid #E8E2C7',fontFamily:font}}><div style={{minWidth:0,flex:'1 1 260px'}}><h2 style={{margin:0,color:'#202024',fontFamily:font,fontSize:'18px',fontWeight:900,lineHeight:1.6}}>{title}</h2>{description&&<p style={{margin:'4px 0 0',color:'#777982',fontFamily:font,fontSize:'11px',lineHeight:1.8}}>{description}</p>}</div>{action&&<aside style={{display:'flex',maxWidth:'100%',alignItems:'center',justifyContent:'flex-end'}}>{action}</aside>}</header>}
export function IrancellPageScaffold({children,title,subtitle,onBack,actions,className='',fullBleed=false,style={}}){
 const font='"Vazirmatn", Tahoma, Arial, sans-serif';
 return <section className={className||undefined} dir="rtl" style={{boxSizing:'border-box',display:'flex',width:'100%',minWidth:0,maxWidth:'none',minHeight:'100%',flexDirection:'column',gap:'18px',margin:0,padding:fullBleed?0:'clamp(14px,3vw,28px)',direction:'rtl',color:'#202024',background:'#FFFAE0',fontFamily:font,...style}}>
  {(title||onBack||actions)&&<header style={{boxSizing:'border-box',display:'flex',width:'100%',minWidth:0,maxWidth:'none',flexWrap:'wrap',alignItems:'center',gap:'12px',margin:0,padding:'14px',background:'#FFFFFF',border:'1px solid #E7E2CC',borderRadius:'19px',boxShadow:'0 8px 24px rgba(62,52,12,.06)',fontFamily:font}}>
   {onBack&&<button type="button" onClick={onBack} aria-label="بازگشت" style={{boxSizing:'border-box',display:'grid',width:'44px',minWidth:'44px',height:'44px',placeItems:'center',margin:0,padding:0,cursor:'pointer',color:'#202024',background:'#FFF4B5',border:'1px solid #E9D15C',borderRadius:'13px',fontFamily:font}}><span className="material-symbols-outlined" aria-hidden="true" style={{fontFamily:'"Material Symbols Outlined"',fontSize:'22px',lineHeight:1}}>arrow_forward</span></button>}
   <div style={{minWidth:'min(100%,180px)',flex:'1 1 260px'}}>
    {title&&<h1 style={{margin:0,overflowWrap:'anywhere',color:'#202024',fontFamily:font,fontSize:'clamp(18px,2.5vw,22px)',fontWeight:900,lineHeight:1.55}}>{title}</h1>}
    {subtitle&&<p style={{margin:'3px 0 0',color:'#74757C',fontFamily:font,fontSize:'12px',fontWeight:500,lineHeight:1.85}}>{subtitle}</p>}
   </div>
   {actions&&<aside style={{display:'flex',maxWidth:'100%',flex:'0 1 auto',flexWrap:'wrap',alignItems:'center',justifyContent:'flex-end',gap:'8px'}}>{actions}</aside>}
  </header>}
  <div style={{boxSizing:'border-box',display:'block',width:'100%',minWidth:0,maxWidth:'none',flex:'1 1 auto',fontFamily:font}}>{children}</div>
 </section>
}
export function IrancellFilterTabs({items=[],value,onChange,ariaLabel='فیلترها'}){const font='"Vazirmatn", Tahoma, Arial, sans-serif';return <div role="group" aria-label={ariaLabel} dir="rtl" style={{boxSizing:'border-box',display:'flex',width:'100%',minWidth:0,alignItems:'center',gap:'7px',margin:0,padding:'5px',overflowX:'auto',background:'#F1F1F3',border:'1px solid #E2E2E6',borderRadius:'15px',fontFamily:font}}>{items.map(item=>{const active=value===item.id;return <button type="button" key={item.id} aria-pressed={active} disabled={item.disabled} onClick={()=>onChange?.(item.id)} style={{boxSizing:'border-box',display:'inline-flex',minWidth:'max-content',minHeight:'40px',alignItems:'center',justifyContent:'center',gap:'7px',margin:0,padding:'8px 13px',cursor:item.disabled?'not-allowed':'pointer',color:active?'#171719':'#686970',background:active?'#FFD100':'transparent',border:`1px solid ${active?'#E7BD00':'transparent'}`,borderRadius:'11px',fontFamily:font,fontSize:'11px',fontWeight:active?900:700,opacity:item.disabled?0.55:1}}><span style={{fontFamily:font}}>{item.label}</span>{item.count!==undefined&&<b style={{display:'grid',minWidth:'20px',height:'20px',placeItems:'center',padding:'0 5px',background:active?'rgba(255,255,255,.52)':'#FFFFFF',borderRadius:'999px',fontFamily:font,fontSize:'9px'}}>{IrancellFormatPersianNumber(item.count)}</b>}</button>})}</div>}
export function IrancellToggleRow({title,description,checked,onChange,disabled=false,loading=false}){const blocked=disabled||loading,font='"Vazirmatn", Tahoma, Arial, sans-serif';return <div dir="rtl" style={{boxSizing:'border-box',display:'grid',width:'100%',minWidth:0,gridTemplateColumns:'minmax(0,1fr) 52px',alignItems:'center',gap:'14px',margin:0,padding:'14px 0',borderBottom:'1px solid #EEE9D4',fontFamily:font,opacity:disabled?0.58:1}}><div style={{display:'flex',minWidth:0,flexDirection:'column',gap:'3px'}}><strong style={{color:'#202024',fontFamily:font,fontSize:'13px',fontWeight:900,lineHeight:1.6}}>{title}</strong>{description&&<small style={{color:'#777982',fontFamily:font,fontSize:'10px',lineHeight:1.8}}>{description}</small>}</div><button type="button" role="switch" aria-checked={Boolean(checked)} aria-label={title} disabled={blocked} onClick={()=>onChange?.(!checked)} style={{boxSizing:'border-box',position:'relative',display:'block',width:'52px',height:'30px',margin:0,padding:'3px',cursor:blocked?'not-allowed':'pointer',background:checked?'#FFD100':'#D8D8DD',border:`1px solid ${checked?'#E7BD00':'#C8C9CE'}`,borderRadius:'999px',fontFamily:font,opacity:blocked?0.65:1}}><span style={{position:'absolute',top:'3px',insetInlineStart:checked?'25px':'3px',display:'block',width:'22px',height:'22px',background:'#FFFFFF',border:'1px solid rgba(32,32,36,.12)',borderRadius:'50%',boxShadow:'0 2px 7px rgba(32,32,36,.16)',transition:'inset-inline-start .18s ease'}}/></button></div>}
export function IrancellStatusBanner({tone='info',title,children,action}){const Icon=tone==='success'?CheckCircle2:tone==='danger'?AlertTriangle:tone==='warning'?AlertTriangle:ShieldCheck,font='"Vazirmatn", Tahoma, Arial, sans-serif',tones={info:{color:'#315E86',background:'#EDF6FF',borderColor:'#C8DDF0'},success:{color:'#21663D',background:'#E9F7EE',borderColor:'#BFE5CC'},warning:{color:'#765F00',background:'#FFF7CE',borderColor:'#F0D763'},danger:{color:'#A12626',background:'#FFF0F0',borderColor:'#F1C7C7'}},selected=tones[tone]||tones.info;return <aside role={tone==='danger'?'alert':'status'} dir="rtl" style={{boxSizing:'border-box',display:'grid',width:'100%',minWidth:0,gridTemplateColumns:'24px minmax(0,1fr) auto',alignItems:'center',gap:'11px',margin:0,padding:'13px 14px',color:selected.color,background:selected.background,border:`1px solid ${selected.borderColor}`,borderRadius:'15px',fontFamily:font}}><Icon size={21}/><div style={{display:'flex',minWidth:0,flexDirection:'column',gap:'2px'}}>{title&&<strong style={{fontFamily:font,fontSize:'12px',fontWeight:900,lineHeight:1.6}}>{title}</strong>}{children&&<p style={{margin:0,fontFamily:font,fontSize:'11px',fontWeight:600,lineHeight:1.8}}>{children}</p>}</div>{action&&<span style={{display:'inline-flex',maxWidth:'100%',alignItems:'center'}}>{action}</span>}</aside>}
export function IrancellStateView({state='empty',title,description,action}){return <div style={{boxSizing:'border-box',display:'block',width:'100%',minWidth:0,maxWidth:'none',margin:0,padding:0,fontFamily:'"Vazirmatn", Tahoma, Arial, sans-serif'}}><IrancellStatePanel state={state} title={title} description={description} action={action}/></div>}
export function IrancellBottomSheet({open,title,children,onClose,actions}){return <IrancellModal open={open} title={title} onClose={onClose} actions={actions} variant="sheet">{children}</IrancellModal>}
export function IrancellChistiComposer({value='',onChange,onSubmit,placeholder='سؤال خود را بنویسید…',loading=false,disabled=false,onAttach,attachmentName='',submitLabel='ارسال'}){const font='"Vazirmatn", Tahoma, Arial, sans-serif',blocked=disabled||loading;function submit(event){event.preventDefault();if(!blocked&&String(value||'').trim())onSubmit?.(event)}return <form onSubmit={submit} dir="rtl" style={{boxSizing:'border-box',display:'grid',width:'100%',minWidth:0,gridTemplateColumns:'minmax(0,1fr) auto auto',alignItems:'end',gap:'8px',margin:0,padding:'8px',background:'#FFFFFF',border:'1px solid #D9D9DE',borderRadius:'17px',fontFamily:font}}><div style={{display:'flex',minWidth:0,flexDirection:'column',gap:'4px'}}>{attachmentName&&<small style={{color:'#725F00',fontFamily:font,fontSize:'9px',fontWeight:800}}>پیوست: {attachmentName}</small>}<textarea value={value} onChange={event=>onChange?.(event.target.value)} placeholder={placeholder} disabled={blocked} rows={1} style={{boxSizing:'border-box',display:'block',width:'100%',minWidth:0,minHeight:'40px',maxHeight:'160px',margin:0,padding:'9px 10px',resize:'vertical',color:'#202024',background:'transparent',border:0,borderRadius:'10px',outline:'none',fontFamily:font,fontSize:'12px',fontWeight:600,lineHeight:1.8}}/></div>{onAttach&&<button type="button" onClick={onAttach} disabled={blocked} aria-label="افزودن پیوست" style={{boxSizing:'border-box',display:'grid',width:'40px',height:'40px',placeItems:'center',margin:0,padding:0,cursor:blocked?'not-allowed':'pointer',color:'#5F6067',background:'#F2F2F4',border:'1px solid #E1E1E5',borderRadius:'11px',fontFamily:font,opacity:blocked?0.55:1}}><UploadCloud size={20}/></button>}<IrancellButton type="submit" loading={loading} disabled={disabled||!String(value||'').trim()} size="sm">{submitLabel}</IrancellButton></form>}